### ISSUE TITLE
Cannot find module 'eslint-plugin-react' with Node 4.2.6 (5.6 works)

### ISSUE THREAD

**Issue by knownasilya** [feross/snazzy#8]
```
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
  at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.module.exports.load (/Users/iradchenko/sandbox/core/node_modules/eslint/lib/config/plugins.js:116:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (/Users/iradchenko/sandbox/core/node_modules/eslint/lib/config/plugins.js:134:21)
    at processText (/Users/iradchenko/sandbox/core/node_modules/eslint/lib/cli-engine.js:158:17)
    at processFile (/Users/iradchenko/sandbox/core/node_modules/eslint/lib/cli-engine.js:227:18)
    at executeOnFile (/Users/iradchenko/sandbox/core/node_modules/eslint/lib/cli-engine.js:602:23)
```

Not sure why I'd need to install this, since I'm not using react. Seems like a dep is missing somewhere..

**Comment by feross** [comment]
Can you try deleting your `node_modules` folder and re-installing everything?

Also, what version of node are you using?

**Comment by knownasilya** [comment]
Tried that, same result. I'm using node 4.2.6 and npm 2.14.12.

**Comment by knownasilya** [comment]
npm 2.14.2

**Comment by knownasilya** [comment]
It does work in Node 5.6

**Comment by feross** [comment]
Can you run `./node_modules/.bin/snazzy --version` and paste the result?

**Comment by feross** [comment]
Also, can you share if you're also depending on `eslint` or `standard` separately, in addition to `snazzy` in your `package.json`?

**Comment by knownasilya** [comment]
6.0.5 for the command. Yes I also have 

```
    "eslint": "^2.0.0",
    "eslint-config-standard": "^5.1.0",
    "eslint-plugin-promise": "^1.0.8",
    "eslint-plugin-standard": "^1.3.0",
    "babel-eslint": "^4.0.10"
```

**Comment by knownasilya** [comment]
@feross any ideas?

**Comment by knownasilya** [comment]
https://travis-ci.org/Strider-CD/core/jobs/110125650#L496

**Comment by feross** [comment]
Since you're depending directly on `eslint`, npm2 is not bothering to install `eslint` into `standard`'s `node_modules` folder. So when standard does `require('eslint')` it's getting the top-level copy of `eslint`. That's usually not a problem, and happens all the time with npm.

But, it causes problems when `eslint` goes to `require('eslint-plugin-react`)`inside of snazzy. Because`eslint`is hoisted out to the top level, it's not going to find`eslint-plugin-react`where it lives inside of`snazzy/node_modules/standard/node_modules/eslint-plugin-react`.

Quick fix for you is to also install `eslint-plugin-react` at the top-level.

PRs for the real fix are here: https://github.com/Flet/standard-engine/pull/73 https://github.com/feross/standard/pull/427

**Comment by feross** [comment]
Released as standard 6.0.6.

**Comment by knownasilya** [comment]
Fix confirmed, just reran the build (reinstall snazzy).

**Comment by feross** [comment]
great, thanks for letting me know!

**Comment by feross** [comment]
Sorry, I had to revert this change in `standard` v6.0.7 because it caused a much worse issue: https://github.com/feross/standard/issues/429

We'll have to hold out for a proper fix from eslint: https://github.com/eslint/eslint/issues/5175

**Comment by feross** [comment]
I suggest just installing `eslint-plugin-react` at the top level of your project, or removing the dependency on `eslint` at the top-level to make things work for now.

**Comment by knownasilya** [comment]
Was trying to use codeclimate eslint engine, so I might move away from snazzy and use https://github.com/jden/standard-codeclimate, but it's outdated.. was hoping to use latest eslint.

**Comment by feross** [comment]
@knownasilya You should talk with @jden. He's probably fine with updating the standard version in `standard-codeclimate`.
